### PR TITLE
Coroutines and ktor for KMP

### PR DESCRIPTION
**Pull request by socampomeli**
# Descripción
   Se añade Coroutines y KTor.

Tamaño de cada dependencia:

Coroutines -> se mantiene la misma de Android
ktor-client-core -> 91kb
ktor-client-content-negotiation -> 3kb
ktor-serialization-kotlinx-json -> 5kb

Por ahora estas libs solo estan disponibles para el proyecto de Realtime Communication (RTC). 

El uso de KTOR se decidio porque es posible comunicar a servidores SSE . Las librerias de Meli de Networking (ios) y resclient (Android) tambien son usadas en este proyecto para obtener los headers y obtener una comunicación efectiva hacia APIs dentro de Meli.

master -> [link](https://gradle.adminml.com/s/6uxq55hwihcw6)
rtc. mobile -> [link](https://gradle.adminml.com/s/tpyszfzkm4q4e)

**COMPARACIÓN DE MASTER CON RTC MOBILE (APP ML)**

[Link de diferencia de dependencias](https://gradle.adminml.com/c/tpyszfzkm4q4e/6uxq55hwihcw6/dependencies )

Arbol de dependencias implementando la lib desde Mercado Libre:

>  com.mercadolibre.android.rtc_mobile:realtime:EXPERIMENTAL-0.1.0-20240506190957
|    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.10 (*)
|    +--- androidx.appcompat:appcompat:1.3.1 -> 1.5.1 (*)
|    +--- com.mercadolibre.android.commons:core:30.+ -> 36.1.0 (*)
|    +--- com.mercadolibre.android.commons:utils:30.+ -> 36.1.0 (*)
|    \--- io.ktor:ktor-client-android:2.2.1
|         \--- io.ktor:ktor-client-android-jvm:2.2.1
|              +--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.20 -> 1.8.10 (*)
|              +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.20 -> 1.8.10 (*)
|              +--- org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.6.4
|              |    +--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4 -> 1.5.2 (*)
|              |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-bom:1.6.4 (*)
|              +--- org.slf4j:slf4j-api:1.7.36
|              +--- io.ktor:ktor-client-core:2.2.1
|              |    \--- io.ktor:ktor-client-core-jvm:2.2.1
|              |         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.20 -> 1.8.10 (*)
|              |         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.20 -> 1.8.10 (*)
|              |         +--- org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.6.4 (*)
|              |         +--- org.slf4j:slf4j-api:1.7.36
|              |         +--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4 -> 1.5.2 (*)
|              |         +--- io.ktor:ktor-http:2.2.1
|              |         |    \--- io.ktor:ktor-http-jvm:2.2.1
|              |         |         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.20 -> 1.8.10 (*)
|              |         |         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.20 -> 1.8.10 (*)
|              |         |         +--- org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.6.4 (*)
|              |         |         +--- org.slf4j:slf4j-api:1.7.36
|              |         |         +--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4 -> 1.5.2 (*)
|              |         |         +--- io.ktor:ktor-utils:2.2.1
|              |         |         |    \--- io.ktor:ktor-utils-jvm:2.2.1
|              |         |         |         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.20 -> 1.8.10 (*)
|              |         |         |         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.20 -> 1.8.10 (*)
|              |         |         |         +--- org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.6.4 (*)
|              |         |         |         +--- org.slf4j:slf4j-api:1.7.36
|              |         |         |         +--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4 -> 1.5.2 (*)
|              |         |         |         +--- io.ktor:ktor-io:2.2.1
|              |         |         |         |    \--- io.ktor:ktor-io-jvm:2.2.1
|              |         |         |         |         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.20 -> 1.8.10 (*)
|              |         |         |         |         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.20 -> 1.8.10 (*)
|              |         |         |         |         +--- org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.6.4 (*)
|              |         |         |         |         +--- org.slf4j:slf4j-api:1.7.36
|              |         |         |         |         +--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4 -> 1.5.2 (*)
|              |         |         |         |         \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.7.20 -> 1.8.10
|              |         |         |         \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.7.20 -> 1.8.10
|              |         |         \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.7.20 -> 1.8.10
|              |         +--- io.ktor:ktor-events:2.2.1
|              |         |    \--- io.ktor:ktor-events-jvm:2.2.1
|              |         |         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.20 -> 1.8.10 (*)
|              |         |         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.20 -> 1.8.10 (*)
|              |         |         +--- org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.6.4 (*)
|              |         |         +--- org.slf4j:slf4j-api:1.7.36
|              |         |         +--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4 -> 1.5.2 (*)
|              |         |         +--- io.ktor:ktor-http:2.2.1 (*)
|              |         |         +--- io.ktor:ktor-utils:2.2.1 (*)
|              |         |         \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.7.20 -> 1.8.10
|              |         +--- io.ktor:ktor-websocket-serialization:2.2.1
|              |         |    \--- io.ktor:ktor-websocket-serialization-jvm:2.2.1
|              |         |         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.20 -> 1.8.10 (*)
|              |         |         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.20 -> 1.8.10 (*)
|              |         |         +--- org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.6.4 (*)
|              |         |         +--- org.slf4j:slf4j-api:1.7.36
|              |         |         +--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4 -> 1.5.2 (*)
|              |         |         +--- io.ktor:ktor-http:2.2.1 (*)
|              |         |         +--- io.ktor:ktor-serialization:2.2.1
|              |         |         |    \--- io.ktor:ktor-serialization-jvm:2.2.1
|              |         |         |         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.20 -> 1.8.10 (*)
|              |         |         |         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.20 -> 1.8.10 (*)
|              |         |         |         +--- org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.6.4 (*)
|              |         |         |         +--- org.slf4j:slf4j-api:1.7.36
|              |         |         |         +--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4 -> 1.5.2 (*)
|              |         |         |         +--- io.ktor:ktor-http:2.2.1 (*)
|              |         |         |         +--- io.ktor:ktor-websockets:2.2.1
|              |         |         |         |    \--- io.ktor:ktor-websockets-jvm:2.2.1
|              |         |         |         |         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.20 -> 1.8.10 (*)
|              |         |         |         |         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.20 -> 1.8.10 (*)
|              |         |         |         |         +--- org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.6.4 (*)
|              |         |         |         |         +--- org.slf4j:slf4j-api:1.7.36
|              |         |         |         |         +--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4 -> 1.5.2 (*)
|              |         |         |         |         +--- io.ktor:ktor-http:2.2.1 (*)
|              |         |         |         |         \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.7.20 -> 1.8.10
|              |         |         |         \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.7.20 -> 1.8.10
|              |         |         \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.7.20 -> 1.8.10
|              |         +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.7.20 -> 1.8.10
|              |         \--- org.jetbrains.kotlinx:kotlinx-coroutines-slf4j:1.6.4
|              |              +--- org.slf4j:slf4j-api:1.7.32 -> 1.7.36
|              |              +--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4 -> 1.5.2 (*)
|              |              +--- org.jetbrains.kotlinx:kotlinx-coroutines-bom:1.6.4 (*)
|              |              \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.21 -> 1.8.10 (*)
|              \--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4 -> 1.5.2 (*)

Se puede observar se fuerza coroutines a 1.5.2. 

De igual hay otras librerias que tambien hacen este forzado a 1.5.2 y trabajan bien en las apps.

# Ticket ID
- - #....

    Para más información visitar [Wiki.](https://sites.google.com/mercadolibre.com/mobile/arquitectura/allowlist) 

## En qué apps impacta mi dependencia
- [x] Mercado Libre
- [x] Mercado Pago
- [ ] SmartPOS
- [ ] Alicia: Flex / Logistics
- [ ] WMS
- [ ] Meli Store

## Mi dependencia es:
- [ ] Interna: Libreria/modulo desarrollado in-house en base al ecosistema de Meli.
- [x] Externa: Libreria desarrollada por un externo a Meli. (Google, Airbnb, otros).

## En caso de ser una dependencia interna, se ha agregado una lib .aar o framework (iOS) en nexus sobre el proyecto?
- [ ] Si, adjuntar link a nexus.
- [ ] No

### CODE REVIEW

**Comment by henrikemota** [comment]
cual impacto de appsize agregando esto en las apps?

**Review by eduflores72 — CHANGES_REQUESTED** [review]
bloqueo este PR, debido a que son libs cross que pueden afectar a otros equipos, debemos validar en que consiste actualizar la libs de kotlin coroutine.

**Review by abruno- — CHANGES_REQUESTED** [review]
@socampomeli 
no tenemos un analisis formal de estas nuevas libs, podran compartir el analisis que hicieron ?
veo q agregamos kotlinx-coroutines-core, se reviso como quedan las dependencias transitivas ?

**Comment by socampomeli** [comment]
Hola equipo, hemos puesto la misma version de coroutines que en Android. Quedamos pendientes para analizar lo de Ktor con el peso que aportaria y las transitivas.

**Review by abruno- — APPROVED** [review]

**Review by eduflores72 — APPROVED** [review]

**Pull request merged**
